project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: news.qmd
        text: News

format:
  html:
    theme: [simplex, custom.scss]
    fontsize: 1.05em
    linestretch: 1.5
    mainfont: "sans-serif"
    toc: true
    toc-title: "<br><br><br>"
    link-external-newwindow: false
    minimal: true
    code-tools: false
    format-links: false
