project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: news.qmd
        text: News

format:
  html:
    theme:
      light: [simplex, custom.scss]
      dark: [cyborg, custom_dark.scss]
    fontsize: 0.95em
    linestretch: 1.4
    mainfont: "sans-serif"
    toc: true
    toc-title: "<br><br><br>"
    link-external-newwindow: false
    minimal: true
